---
- name: Ensure report directory exists
  file:
    path: "{{ report_dir }}"
    state: directory

- name: Save as JSON
  copy:
    content: "{{ serverless_inventory | to_nice_json }}"
    dest: "{{ report_dir }}/serverless_inventory.json"

- name: Save as CSV
  copy:
    content: |
      cloud,service,name,region,trigger
      {% for item in serverless_inventory %}
      {{ item.cloud }},{{ item.service }},{{ item.name }},{{ item.region }},{{ item.trigger }}
      {% endfor %}
    dest: "{{ report_dir }}/serverless_inventory.csv"

- name: Save as HTML
  copy:
    content: |
      <html><body><h2>Serverless Report</h2><table border="1">
      <tr><th>Cloud</th><th>Service</th><th>Name</th><th>Region</th><th>Trigger</th></tr>
      {% for item in serverless_inventory %}
      <tr><td>{{ item.cloud }}</td><td>{{ item.service }}</td><td>{{ item.name }}</td><td>{{ item.region }}</td><td>{{ item.trigger }}</td></tr>
      {% endfor %}
      </table></body></html>
    dest: "{{ report_dir }}/serverless_inventory.html"

- name: Email report
  mail:
    host: "{{ smtp_host }}"
    port: "{{ smtp_port }}"
    username: "{{ smtp_user }}"
    password: "{{ smtp_pass }}"
    to: "{{ email_to }}"
    subject: "Multi-Cloud Serverless Inventory Report"
    body: "Attached is the serverless inventory report in multiple formats."
    attach:
      - "{{ report_dir }}/serverless_inventory.csv"
      - "{{ report_dir }}/serverless_inventory.json"
      - "{{ report_dir }}/serverless_inventory.html"
